//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiTech_Ryff_2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ReqDate { get; set; }
        public System.DateTime ShipDate { get; set; }
        public int CId { get; set; }
    }
}
