//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitechEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string Title { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> QoH { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> SId { get; set; }
        public int AuthorId { get; set; }
        public string ISBN { get; set; }
    }
}
