//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitechEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Oid { get; set; }
        public int Cid { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string ISBN { get; set; }
        public string BookName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> Total { get; set; }
        public string ClientName { get; set; }
    }
}
